# Generated by Django 5.2.8 on 2025-11-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='nick_player',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='fac_player',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='lives.fac'),
        ),
    ]
