# Generated by Django 5.2.8 on 2025-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0002_canal_nick_player_alter_canal_fac_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='link',
        ),
        migrations.AddField(
            model_name='canal',
            name='link_kick',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='link_tw',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='canal',
            name='link_yt',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
