# Generated by Django 5.2.8 on 2025-11-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0003_remove_canal_link_canal_link_kick_canal_link_tw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='fac_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lives.fac'),
        ),
    ]
