# Generated by Django 5.2.8 on 2025-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0004_alter_canal_fac_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='link_kick',
            field=models.CharField(default='#', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='link_tw',
            field=models.CharField(default='#', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='link_yt',
            field=models.CharField(default='#', max_length=250, null=True),
        ),
    ]
